# Generated by Django 4.2.1 on 2023-05-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=80)),
                ('company', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=80)),
                ('requirements', models.CharField(max_length=80)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_posted', models.DateField()),
            ],
        ),
    ]
